# Generated by Django 6.1.1 on 2026-10-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='geocode_source',
            field=models.TextField(blank=True, null=True),
        ),
    ]
